### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by fluxxus** [davidfitzgibbon/Threeasy#13]
Hey, what is the latest version of `Threeasy`?

If I install with NPM `npm install threeasy` I get the `0.1.13`, but looking at the main repo and [https://threeasy-site.vercel.app/](https://threeasy-site.vercel.app/) it is `0.1.12`.

Thx

**Comment by davidfitzgibbon** [comment]
Apologies for the mixup here, and second for the slow reply!

This should be sorted now, and the latest is 0.1.14! I dont have a great process for updating the version numbers everywhere, and forgot the site. I'll try to improve this in future!
